export const chatRooms: ChatRoom[] = [
  {
    id: "1",
    title: "Manu Arora",
    description: "Chat Room 1 Description",
    isGroup: false,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Neha Singh",
    description: "Chat Room 2 Description",
    isGroup: true,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Rahul Verma",
    description: "Chat Room 3 Description",
    isGroup: false,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Priya Gupta",
    description: "Chat Room 4 Description",
    isGroup: true,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Amit Sharma",
    description: "Chat Room 5 Description",
    isGroup: false,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Sita Devi",
    description: "Chat Room 6 Description",
    isGroup: true,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "7",
    title: "Ravi Kumar",
    description: "Chat Room 7 Description",
    isGroup: false,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "8",
    title: "Anjali Mehta",
    description: "Chat Room 8 Description",
    isGroup: true,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "9",
    title: "Vikram Singh",
    description: "Chat Room 9 Description",
    isGroup: false,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
  {
    id: "10",
    title: "Geeta Rani",
    description: "Chat Room 10 Description",
    isGroup: true,
    $createdAt: new Date(),
    $updatedAt: new Date(),
  },
];
